--- 
- hosts: all 
  connection: local
  tasks: 

    - name: Create a filter
      aci_rest:
        host: '{{ inventory_hostname }}'
        username: '{{ lookup("env", "ANSIBLE_NET_USERNAME")}}'
        password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD")}}'
        path: /api/node/mo/uni/tn-{{TENANT}}/flt-{{FILTER}}.json
        method: post
        content:
          {
           "vzFilter":{
      "attributes":{
         "name":"{{FILTER}}",
         "status":"created"
      },
      "children":[
         {
            "vzEntry":{
               "attributes":{
                  "name":"{{FILTERENTRY}}",
                  "etherT":"ip",
                  "prot":"tcp",
                  "dFromPort":"{{PORT}}",
                  "dToPort":"unspecified",
                  "status":"created"
               },
               "children":[

               ]
            }
         }
      ]
   }
          }
        validate_certs: no
      delegate_to: localhost